model: ../runs/gtx1650s_stage1_head_warmup/weights/best.pt
data: data.yaml
imgsz: 640
epochs: 60
batch: 2
device: 0
workers: 2
project: ../runs
name: gtx1650s_stage2_full_finetune
optimizer: AdamW
lr0: 0.0004
lrf: 0.01
weight_decay: 0.0005
warmup_epochs: 2
cos_lr: true
patience: 20
freeze: 0
amp: true
cache: false
translate: 0.06
scale: 0.2
fliplr: 0.5
mosaic: 0.25
mixup: 0.0
save: true
plots: true
