model: yolov8n.pt
data: data.yaml
imgsz: 640
epochs: 30
batch: 8
device: 0
workers: 2
project: ../runs
name: gtx1650_stage1_head_warmup
optimizer: AdamW
lr0: 0.001
lrf: 0.01
weight_decay: 0.0005
warmup_epochs: 3
cos_lr: true
patience: 20
freeze: 10
amp: true
cache: false
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.08
scale: 0.25
fliplr: 0.5
mosaic: 0.6
mixup: 0.0
save: true
plots: true
