model: yolov8s.pt
data: ../configs/data.yaml
epochs: 100
imgsz: 640
batch: 4
device: 0
workers: 4
patience: 30
optimizer: AdamW
lr0: 0.0005
lrf: 0.01
weight_decay: 0.0005
warmup_epochs: 2.0
cos_lr: true
freeze: 0
cache: false
amp: true
close_mosaic: 15
hsv_h: 0.015
hsv_s: 0.45
hsv_v: 0.2
translate: 0.05
scale: 0.2
fliplr: 0.5
mosaic: 0.3
mixup: 0.0
project: ../runs
name: final_model
exist_ok: true
