model: ../runs/gtx1650_stage1_head_warmup/weights/best.pt
data: data.yaml
imgsz: 640
epochs: 80
batch: 4
device: 0
workers: 2
project: ../runs
name: gtx1650_stage2_full_finetune
optimizer: AdamW
lr0: 0.0005
lrf: 0.01
weight_decay: 0.0005
warmup_epochs: 2
cos_lr: true
patience: 25
freeze: 0
amp: true
cache: false
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
translate: 0.06
scale: 0.2
fliplr: 0.5
mosaic: 0.3
mixup: 0.0
save: true
plots: true
