model: ../runs/garbage_stage1_head_warmup/weights/best.pt
data: ../configs/data.yaml
epochs: 120
imgsz: 640
batch: 16
device: 0
workers: 8
patience: 40
optimizer: AdamW
lr0: 0.0005
lrf: 0.01
weight_decay: 0.0005
warmup_epochs: 2.0
cos_lr: true
multi_scale: 0.25
freeze: 0
cache: false
amp: true
close_mosaic: 15
hsv_h: 0.015
hsv_s: 0.5
hsv_v: 0.25
translate: 0.05
scale: 0.25
fliplr: 0.5
mosaic: 0.3
mixup: 0.0
project: ../runs
name: garbage_stage2_full_finetune
exist_ok: true
